### ISSUE TITLE
Issues on coverage report

### ISSUE THREAD

**Issue by vvatelot** [alexanderdamiani/pytester-cov#1]
Hello @alexanderdamiani , thanks for the brilliant contribution! It was exactly what I was looking for.
But it seems I have issues on my repo:
![image](https://user-images.githubusercontent.com/12939091/118321843-7e625b00-b4fe-11eb-84ff-1ce55fafa87c.png)
The table comment is malformed :cry: 

And the coverage single failed test gives an error but it should be OK. Here is my repo:
https://github.com/cnumr/ecoindex_cli/blob/test/cli/.github/workflows/quality.yml

How could I help ?

**Comment by alexanderdamiani** [comment]
Hey @vvatelot thanks for bringing this up. After reviewing the file in your [link](https://github.com/cnumr/ecoindex_cli/blob/test/cli/.github/workflows/quality.yml), you aren't running the pytest check prior to the coverage check. If I try to run just `pytest -v` on your repo, I get errors. That means the `pytest` tests that you wrote have issues. I recommend before running the `pytester-cov` action, you first run `pytest -v` on the repo. If there are any errors there, the action will fail and not get to the coverage check.

Checking pytest code coverage only makes sense if your tests actually work. Please give this a shot and let me know if this solves your issues.

**Comment by vvatelot** [comment]
Hello @alexanderdamiani not sure to understand... When I run pytest, I do not have any issue:
![image](https://user-images.githubusercontent.com/12939091/118412223-1300c080-b699-11eb-9b1a-406d62b22159.png)
:thinking:

**Comment by alexanderdamiani** [comment]
Can you try running it in your `.github/workflows/quality.yml` workflow file on a pull request? So before you run the `pytester-cov` action, run `pytest -v` and let me know if there are any errors. You can use the code below if you like.

    - name: pytest
      run: python -m pytest

**Comment by vvatelot** [comment]
Done here : https://github.com/cnumr/ecoindex_cli/pull/26

**Comment by alexanderdamiani** [comment]
Can you add the `pytester-cov` action to [your workflow file](https://github.com/cnumr/ecoindex_cli/blob/test/tes-pytest-cov/.github/workflows/quality.yml), initiate another pull request, and let me know if the table comment is still formatted wrongly?

**Comment by vvatelot** [comment]
Done here: https://github.com/cnumr/ecoindex_cli/runs/2604362283?check_suite_focus=true
Here is the comment result: https://github.com/cnumr/ecoindex_cli/pull/26#commitcomment-50936059 

As you can see, the table is broken and the results do not match with wath we get with the command line:
![image](https://user-images.githubusercontent.com/12939091/118550735-545aa400-b75d-11eb-9bcb-ae1b530911c8.png)

**Comment by alexanderdamiani** [comment]
Thanks for helping me diagnose the issue. I realize the issue is the bash script running in the `pytester-cov` GitHub Action is prepending `/github/workspace` to the paths of the files, so there are `ImportErrors` causing incorrect coverage amounts and errors.

I've been working on this all night and will come back to it more this week to find a solution.

**Comment by vvatelot** [comment]
Hello @alexanderdamiani do not worry, there is no rush ! :smile: 
I really appreciate you are taking time to improve this, but do not sacrifice your nights  :wink:

Let me know if I can help you: Code review, end to end test, provide a `.coverage` file ?...

**Comment by alexanderdamiani** [comment]
@vvatelot I figured out what the issue was. The action itself runs in a separate Docker container, and doesn't have access to the packages installed from your `requirements.txt` file that were installed earlier in the workflow file. Therefore, the `requirements.txt` file must be reinstalled in the Docker container.

I added a new version [v1.1.0](https://github.com/alexanderdamiani/pytester-cov/tree/v1.1.0). Please try using it in your project and let me know if you continue to have any issues.

**Comment by vvatelot** [comment]
Hello @alexanderdamiani I can confirm you this is working fine now!
Thank you! I close the issue as you fixed my issue :wink:
